# Exercicios

Para praticar os métodos aprendidos no decorrer dessa aula e também aprender novos, vamos realizar 
algumas análises utilizando um arquivo csv diferente: alunos.csv.

1) Importe o arquivo alunos.csv e armazene seu conteúdo em um DataFrame Pandas.

2) Visualize as primeiras 7 linhas do DataFrame e as 5 últimas.

3) Confira a quantidade de linhas e colunas desse DataFrame.

4) Explore as colunas do DataFrame e analise os tipos dos dados presentes em cada coluna.

Extra: Calcule algumas estatísticas descritivas básicas dos dados do DataFrame (média, 
desvio padrão, etc). Dica: pesquise pelo método describe.

In [1]:
import pandas as pd

csv_alunos = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'
data_alunos = pd.read_csv(csv_alunos)

# General information

In [2]:
data_alunos.head(7)

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True
5  Bruna     23    NaN     False
6   Dara     21    7.0      True

In [3]:
data_alunos.tail(5)

      Nome  Idade  Notas  Aprovado
13   Mirla     25    9.0      True
14   Paulo     37    NaN     False
15  Mylena     29    7.0      True
16   Lucas     33    NaN     False
17   Nadia     34    8.0      True

In [4]:
data_alunos.shape

(18, 4)

In [5]:
data_alunos.dtypes

Nome         object
Idade         int64
Notas       float64
Aprovado       bool
dtype: object

In [6]:
data_alunos.describe()

           Idade      Notas
count  18.000000  12.000000
mean   25.500000   6.800000
std     6.070662   2.204953
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000

# Média Idade e Notas

In [7]:
idade_notas=data_alunos[['Idade','Notas']]

idade_notas.mean()

Idade    25.5
Notas     6.8
dtype: float64

# Desvio Idade e Notas

In [8]:
idade_notas.std()

Idade    6.070662
Notas    2.204953
dtype: float64

# Desafio

1- Descobrir exatamente quantas linhas na sua tabela inteira têm essas notas vazias/faltantes

2- Ver uma tabela apenas com os alunos que tiraram notas maiores que 8.0.

# Notas Vazia/Faltantes

In [9]:
qtd_alunos_na=data_alunos['Notas'].isnull().sum(skipna=False)
qtd_alunos_na

np.int64(6)

# Alunos com notas maiores que 8.0

In [10]:
[data_alunos['Notas'] > 8.0 ]

[0     False
 1     False
 2     False
 3     False
 4      True
 5     False
 6     False
 7     False
 8     False
 9     False
 10    False
 11    False
 12     True
 13     True
 14    False
 15    False
 16    False
 17    False
 Name: Notas, dtype: bool]

In [11]:
nota_maior_8= data_alunos[data_alunos['Notas'] > 8.0 ]
nota_maior_8

         Nome  Idade  Notas  Aprovado
4        Beto     21   10.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True